spring:
  application:
    :name: tev

# Mysql Setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tev
    username: ${SQL_UN}
    password: ${SQL_PW}

# JPA Setting
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true

    hibernate:
      ddl-auto: update

# env Setting
  config:
    import: optional:file:.env[.properties]

# JWT - HS512
jwt:
  secret: ASwidfEJisnenjkIEKNieiKQ38V93YR7894hnfn38urh37s3jEYR83HDF8h93nfjhedf8wkj93h8ehASUJe8cxWhudSeuxhe23x3hnd8

server:
  port: 8090