spring:
  application:
    :name: tev

# Mysql Setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tev
    username: ${SQL_UN}
    password: ${SQL_PW}

# JPA Setting
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true

    hibernate:
      ddl-auto: update

# env Setting
  config:
    import: optional:file:.env[.properties]



server:
  port: 8090